### Diet API 테스트 파일

### 특정 날짜의 식사 기록 조회
@date=2024-01-15
GET {{baseUrl}}/{{apiVersion}}/diets/daily?date={{date}}
Accept: application/json
X-USER-ID: 1

###

### 특정 월의 식사 기록 조회
@yearMonth=2025-09
GET {{baseUrl}}/{{apiVersion}}/diets/monthly?yearMonth={{yearMonth}}
Accept: application/json
X-USER-ID: 44
###

### 식단 생성
POST {{baseUrl}}/{{apiVersion}}/diets
Content-Type: application/json
X-USER-ID: 1

{
  "mealType": "BREAKFAST",
  "consumedAt": "2025-09-25T08:30:00",
  "dietFoods": [
    {
      "foodId": 1,
      "intake": 2
    },
    {
      "foodId": 2,
      "intake": 1
    }
  ]
}

###

### 식단 수정
@dietId = 1
POST {{baseUrl}}/{{apiVersion}}/diets/{{dietId}}
Content-Type: application/json
X-USER-ID: 1

{
  "mealType": "BREAKFAST",
  "consumedAt": "2025-09-25T09:30:00",
  "dietFoods": [
    {
      "foodId": 1,
      "intake": 10
    }
  ]
}